#!/bin/bash

# compile haskell program of one source file
# example:

# ./build 12a


opts="
 -O2                      \
 -XBangPatterns           \
 -funbox-strict-fields    \
"
#echo ${opts}
ghc ${opts} $1.hs -o $1.elf

