#!/bin/bash

# compile haskell program of one source file
# example:

# ./build 12a.hs

#  -O2                      \
opts="
 -XBangPatterns           \
 -funbox-strict-fields    \
"
#echo ${opts}
ghc ${opts} --make $1

